### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by Carl2213** [humhub/sharebetween#16]
[sharebetween.gz](https://github.com/humhub-contrib/sharebetween/files/5255841/sharebetween.gz)

Thanks to [dajanvulaj](https://github.com/dajanvulaj/humhub-sharebetween) for his contributions. 

## Done

- [x] Sharing to profile works
- [x] Sharing to spaces works
- [x] Privacy check (share button only appears on public posts) works
- [x] Working on latest Humhub version (1.6.3) with no errors

## TODO

- [ ] Show attached media from original post
- [ ] Add a caption to the shared post (post create form in share modal)
- [ ] Show Like/Comment/etc buttons and counters for the original post within the shared post, allowing access to the original discussion
